//  Problem:
//  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//  By starting with 1 and 2, the first 10 terms will be:
//  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//  By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//  find the sum of the even-valued terms.

#include <stdio.h>

int main()
{
    int a = 1, b = 0, fibonacci = 0;
    long long sumEven = 0;

    while (fibonacci < 4000000)
    {
        //Fn = Fn-1 + Fn-2
        fibonacci = a + b;
        printf("%d\n", fibonacci);
        if (fibonacci % 2 == 0)
        {
            sumEven += fibonacci;
        }

        b = a;
        a = fibonacci;
    }
    printf("The sum of all even numbers in the fibonacci sequence above is = %lld\n", sumEven);
    return 0;
}